#!/usr/bin/env python3
"""Feed the dashboard's live "Expected vs actual" panel with prose generated by the running model.

The trainer only writes Noul bootstrap and stage-end Jev evaluation samples, so during prose-focused training
that panel never shows prose. Every few minutes this asks the live trainer (through the local portal, which is
what the public dashboard uses) one held-out prose question from datasets/fits/prose-fit-v1.jsonl, then appends
an evaluation sample with the expected answer, the actual generated text, and a byte-prefix score.
Fit-set items are never trained on, so exact answers measure generalization, not memorization.
"""

from __future__ import annotations

import argparse
import json
import os
import time
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

REPO = Path(__file__).resolve().parent.parent
FIT = REPO / "datasets/fits/prose-fit-v1.jsonl"


def normalize(text: str) -> str:
    return " ".join(text.strip().lower().split()).rstrip(".")


def ask(url: str, item: dict, request_id: str, max_bytes: int, timeout: float) -> tuple[str | None, str | None]:
    payload = {"id": request_id, "inputs": {"prompt": item["prompt"], "modality": "prose"},
               "outputs": {"answer": {"type": "text", "instructions": item["instructions"], "max_bytes": max_bytes}}}
    request = Request(url, data=json.dumps(payload).encode(), headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urlopen(request, timeout=timeout) as response:
            body = json.load(response)
    except HTTPError as error:
        return None, f"HTTP {error.code}: {error.read(300).decode(errors='replace')}"
    except (URLError, TimeoutError, OSError) as error:
        return None, f"transport: {error}"
    answer = (body.get("answers") or {}).get("answer") or {}
    if not body.get("ok") or "text" not in answer:
        return None, "trainer returned no text answer"
    return answer["text"], None


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--url", default="http://127.0.0.1:8799/api/test")
    parser.add_argument("--telemetry", type=Path, default=Path("/bulk-storage/connectome-merc/river-multimodal-runs/current"))
    parser.add_argument("--interval", type=float, default=360.0)
    parser.add_argument("--max-bytes", type=int, default=32)
    args = parser.parse_args()
    items = [item for item in map(json.loads, FIT.read_text().splitlines()) if item["kind"] == "prose"]
    index = int(time.time() // args.interval) % len(items)
    while True:
        item = items[index % len(items)]
        index += 1
        try:
            state = json.loads((args.telemetry / "state.json").read_text())
        except (FileNotFoundError, json.JSONDecodeError):
            state = {}
        if not str(state.get("status", "")).startswith("training"):
            time.sleep(30)  # the portal refuses probes between stages
            index -= 1
            continue
        actual, error = ask(args.url, item, f"live-prose-{item['id']}-{int(time.time())}", args.max_bytes, 640)
        if actual is not None:
            expected = item["answer"]
            prefix = 0
            for want, got in zip(expected.encode(), actual.encode()):
                if want != got:
                    break
                prefix += 1
            sample = {
                "schema": "river-evaluation-output-telemetry-v1", "kind": "evaluation",
                "dataset_id": "prose-fit-v1 (held out, never trained)", "task": f"Prose answer · {item['id']}",
                "output_type": "prose", "input_modality": "prose",
                "input": {"prompt": item["prompt"], "instructions": item["instructions"]},
                "expected": expected, "predicted": actual,
                "matched": normalize(actual).startswith(normalize(expected)),
                "accuracy": prefix / len(expected.encode()),
                "diff": f"first {prefix}/{len(expected.encode())} expected bytes correct",
                "batch": state.get("batch"), "epoch": state.get("epoch"),
                "evaluated_at_unix_ms": int(time.time() * 1000),
            }
            with (args.telemetry / "samples.jsonl").open("a") as stream:
                stream.write(json.dumps(sample, separators=(",", ":")) + "\n")
            print(f"{item['id']}: {actual!r}", flush=True)
        else:
            print(f"{item['id']}: no answer ({error})", flush=True)
        time.sleep(args.interval)


if __name__ == "__main__":
    os.nice(5)
    main()
